### ISSUE TITLE
files.json

### ISSUE THREAD

**Issue by ElvisBM** [sergiolopes/shopping#1]
Sérgio,  qual a idéia do files.json? Pois vi que o conteúdo não é um json.

Vi que dentro do service-worker.js, você tem o mesmo conteúdo, qual a necessidade do files.json?

**Comment by sergiolopes** [comment]
É gerado por uma task no gulp pra eu colocar no service worker. 

https://github.com/sergiolopes/shopping/blob/master/gulpfile.js#L72-L85

No site final é lixo, não precisava. Talvez devesse apagar no build :-P

**Comment by ElvisBM** [comment]
Sergio, valeu, vou olhar melhor todo o código
