### ISSUE TITLE
Referencia na pwa-list

### ISSUE THREAD

**Issue by lnfnunes** [sergiolopes/shopping#2]
Fala @sergiolopes, blz ?
Cara, espero que não ache ruim, mas tomei a liberdade de sugerir seu demo na [pwa-list do Paul Irish](https://github.com/paulirish/pwa-list/pull/1/commits).

Coloquei como _SL-Shopping_

Achei bem bacana teu app e legal compartilhar numa lista de renome (apesar que a oficial é do Opera).
Fique à vontade caso não tenha interesse, ok?
Abs

**Comment by sergiolopes** [comment]
Boa! Valeu
