### ISSUE TITLE
Acessar o repositório com o link do github

### ISSUE THREAD

**Issue by yurimatheus** [sergiolopes/shopping#3]
@sergiolopes conseguir acessar o projeto via url do github mas, quando fiz o fork para meu repositório não consigo acessar colocando meu username.

Você por favor me ajuda a configurar o github para eu acessar? Não tenho ideia de como fazer isso.

**Comment by sergiolopes** [comment]
oi yuri! feito o fork, é só vc clonar na sua maquina com:

```
git clone git@github.com:yurimatheus/shopping.git
```

é pra funcionar de boa... testa aí e me diz

abraço

**Comment by yurimatheus** [comment]
Oi Sérgio, acho que não fui claro.

Eu não sei como configurar para acessar a URL do Github como você fez com o
projeto (sergiolopes.github.io/shopping).. depois de fazer o fork eu tentei
acessar trocando pelo meu username e não foi rsrsrsrs

Até vi os webhooks e ainda assim não consegui entender como configurar

Em seg, 26 de set de 2016 09:54, Sérgio Lopes notifications@github.com
escreveu:

**Comment by sergiolopes** [comment]
saquei!
vai aqui: https://github.com/yurimatheus/shopping/settings
e habilita o GitHub Pages. ele usa a branch gh-pages pra servir.

**Comment by yurimatheus** [comment]
Hummm que massa... Entendi.

Se eu quisesse ter páginas dinâmicas visto que seu exemplo tem várias
páginas estáticas, seria possível?

O Service Works saberia tratar essas páginas dinâmicas?

Em seg, 26 de set de 2016 10:04, Sérgio Lopes notifications@github.com
escreveu:

**Comment by yurimatheus** [comment]
Muito obrigado @sergiolopes ... consegui aqui!

**Comment by sergiolopes** [comment]
que bom!

O github pages só suporta paginas estatisticas ou, no maximo, com jekyll. Nada dinamico...

**Comment by sofiaestrelab** [comment]
que
